// On search results page, not category listings page

export const eligibilitiesMapping = {
  Disability: [
    "All Disabilities",
    "Developmental Disability",
    "Physical Disability",
    "Learning Disability",
    "Intellectual Disability",
    "Visual Impairment",
    "Limited Mobility",
    "Deaf or Hard of Hearing",
  ],
  Families: ["Families", "Families with Babies"],
  Homeless: ["Homeless"],
  Immigrants: ["Immigrants", "Undocumented"],
  "LGBTQ+": ["LGBTQ+", "LGBTQ", "Transgender and Gender Non-Conforming"], // Todo: "LGBTQ" can be removed from array once LGBTQ eligibility has been switched to LGBTQ+ in DB across all environments
  "Mental Health/Substance Use": ["Mental Illness", "Substance Dependency"],
  "Re-Entry": ["Re-Entry", "In Jail"],
  "Seniors (55+ years old)": ["Seniors (55+ years old)"],
  "Transition Aged Youth": ["Transition Aged Youth", "Teens (13-19 years old)"],
  "Trauma Survivors": [
    "Trauma Survivors",
    "Abuse or Neglect Survivors",
    "Domestic Violence Survivors",
    "PTSD",
  ],
  Veterans: ["Veterans"],
};

// Hardcoded catgories in search page sidebar (Can add multiple categories as array)
/* i.e. "Arts, Culture & Identity": [
  "Arts and Creative Expression",
  "Culinary Arts",
  "Culture & Identity",
  "Dance",
  "Digital Media Production",
  "Disability Support",
  "Justice Involvement",
  "LGBTQ+ Support",
  "Summer Programs"
]
*/
export const categoriesMapping = {
  "Basic Needs & Shelter": ["Basic Needs & Shelter"],
  Employment: ["Employment"],
  "Eviction Prevention": ["Eviction Prevention"],
  "Health & Medical": ["Health & Medical"],
  Housing: ["Housing"],
  Legal: ["Legal"],
};

// From DCYF spreadsheet (contains duplicates):
export const our415SubcategoriesWithDuplicates = [
  "Arts & Creative Expression",
  "Culinary Arts",
  "Culture & Identity",
  "Dance",
  "Digital Media Production",
  "Disability Support",
  "Justice Involvement",
  "LGBTQ+ Support",
  "Summer Programs",
  "After & Before School",
  "Childcare",
  "Playgroups",
  "Summer Programs",
  "Academic Support",
  "Alternative Education & GED",
  "College Prep",
  "Computer Class",
  "Disability Support",
  "Financial Education",
  "Foreign Languages",
  "Free City College",
  "Justice Involvement",
  "Learning English",
  "LGBTQ+ Support",
  "Public Schools",
  "Reading & Literacy",
  "SEL (Social Emotional Learning)",
  "Special Education",
  "STEM",
  "Summer Programs",
  "Child Welfare Services",
  "Computer or Internet Access",
  "Disability Support",
  "Legal Services",
  "Family Resource Centers",
  "Family Shelters",
  "Financial Assistance",
  "Food",
  "Adoption & Foster Care",
  "Housing & Rental Assistance",
  "Immigration Assistance",
  "Justice Involvement",
  "LGBTQ+ Support",
  "Parent Education",
  "Support Groups",
  "Teen Parents",
  "Addiction & Recovery",
  "Crisis Intervention",
  "Dental Care",
  "Disability Support",
  "Health Education",
  "Justice Involvement",
  "LGBTQ+ Support",
  "Medical Care",
  "Mental Health",
  "Vision Care",
  "Disability Support",
  "Gardening",
  "Justice Involvement",
  "LGBTQ+ Support",
  "Outdoors",
  "Summer Programs",
  "Physical Fitness",
  "Team Sports",
  "Apprenticeship",
  "Career Exploration",
  "Disability Support",
  "Job Assistance",
  "Justice Involvement",
  "LGBTQ+ Support",
  "Mentorship",
  "Skills & Training",
  "Summer Programs",
  "Vocational Training",
  "Youth Jobs & Internships",
  "Youth Leadership",
];

export const our415Subcategories = new Set(our415SubcategoriesWithDuplicates);
